### ISSUE TITLE
Bug in recover nearest algorithm

### ISSUE THREAD

**Issue by drinckes** [shkschneider/android_OpenLocationCodes#1]
Hi - we recently discovered a bug in the recover or recoverNearest algorithm for Open Location Code. We've fixed it in the libraries in the main github project. To see what changes we made, you can refer to [this issue](https://github.com/google/open-location-code/issues/37), and it's linked pull request, for details on how you can make the fix in your own code.

Thanks for using OLC!

**Comment by shkschneider** [comment]
I have to update my code indeed.
Thanks for the heads-up :)
