### ISSUE TITLE
OLC library bug in recover()

### ISSUE THREAD

**Issue by drinckes** [shkschneider/android_OpenLocationCodes#2]
Hi - just to let you know, we recently fixed a bug in the recover() method that could return an invalid code at extreme latitudes.

I'd suggest you update the code you're using to match the [current version](https://github.com/google/open-location-code/blob/master/java/com/google/openlocationcode/OpenLocationCode.java).

**Comment by shkschneider** [comment]
Nice. Quickly updated. Will test my code and explore your Java version. Thanks.
